test_that("simulate_edqtl_cohort returns consistent, correctly named inputs and truth", {
  co <- simulate_edqtl_cohort(n_donors = 200, n_sites_per_type = 2, n_variants = 4, seed = 3)
  S <- 2 * (4 + 2)
  expect_equal(dim(co$bulk_editing), c(S, 200)); expect_equal(dim(co$coverage), c(S, 200))
  expect_equal(dim(co$genotypes), c(S * 4, 200)); expect_equal(nrow(co$pairs), S * 4)
  expect_identical(rownames(co$bulk_editing), rownames(co$theta))
  expect_identical(colnames(co$bulk_editing), rownames(co$proportions))
  expect_true(all(co$pairs$variant_id %in% rownames(co$genotypes)))
  expect_true(all(abs(rowSums(co$proportions) - 1) < 1e-12))
  expect_true(all(co$bulk_editing >= 0 & co$bulk_editing <= 1)); expect_true(all(co$coverage >= 2))
  expect_true(all(rowSums(co$theta > 0) >= 2))
  nul <- names(co$truth$site_type)[co$truth$site_type == "null"]; expect_true(all(co$truth$beta[nul, ] == 0))
  one <- names(co$truth$site_type)[co$truth$site_type == "only_Monocytes"]
  expect_true(all(co$truth$beta[one, "Monocytes"] > 0) && all(co$truth$beta[one, -2] == 0))
  expect_true(all(co$theta[one, "Monocytes"] > 0))
  expect_true(all(is.na(co$truth$latent$NK[co$theta[, "NK"] == 0, ])))
  expect_equal(dim(co$bulk_expression), dim(co$bulk_editing))
  expect_true(all(grepl("^[0-9]+:[0-9]+:[+-]$", rownames(co$bulk_editing))))
})
