// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sc_variant_stats_cpp
NumericMatrix sc_variant_stats_cpp(NumericMatrix G, IntegerVector rows, IntegerVector cols);
RcppExport SEXP _caEditR_sc_variant_stats_cpp(SEXP GSEXP, SEXP rowsSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type G(GSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cols(colsSEXP);
    rcpp_result_gen = Rcpp::wrap(sc_variant_stats_cpp(G, rows, cols));
    return rcpp_result_gen;
END_RCPP
}
// sc_block_post_cpp
List sc_block_post_cpp(NumericMatrix Mg0, NumericMatrix Mgg, NumericMatrix u, NumericMatrix M00i, NumericVector a0, IntegerMatrix kidx, IntegerMatrix ut, bool want_cov, double piv_tol);
RcppExport SEXP _caEditR_sc_block_post_cpp(SEXP Mg0SEXP, SEXP MggSEXP, SEXP uSEXP, SEXP M00iSEXP, SEXP a0SEXP, SEXP kidxSEXP, SEXP utSEXP, SEXP want_covSEXP, SEXP piv_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Mg0(Mg0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Mgg(MggSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type M00i(M00iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type kidx(kidxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type ut(utSEXP);
    Rcpp::traits::input_parameter< bool >::type want_cov(want_covSEXP);
    Rcpp::traits::input_parameter< double >::type piv_tol(piv_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(sc_block_post_cpp(Mg0, Mgg, u, M00i, a0, kidx, ut, want_cov, piv_tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_caEditR_sc_variant_stats_cpp", (DL_FUNC) &_caEditR_sc_variant_stats_cpp, 3},
    {"_caEditR_sc_block_post_cpp", (DL_FUNC) &_caEditR_sc_block_post_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_caEditR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
