# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.sc_variant_stats_cpp <- function(G, rows, cols) {
    .Call(`_caEditR_sc_variant_stats_cpp`, G, rows, cols)
}

.sc_block_post_cpp <- function(Mg0, Mgg, u, M00i, a0, kidx, ut, want_cov, piv_tol) {
    .Call(`_caEditR_sc_block_post_cpp`, Mg0, Mgg, u, M00i, a0, kidx, ut, want_cov, piv_tol)
}

